### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by peanutthegreat** [nwdamgaard/LogViewer#2]
When you select the same parameter for two or more Y axes you get an unhandled exception. You can click continue and the program keeps functioning though.

Partial error text from selecting "engine speed" for two Y axes:

System.ArgumentException: A chart element with the name 'Engine Speed (rpm)' already exists in the 'SeriesCollection'.
   at System.Windows.Forms.DataVisualization.Charting.ChartNamedElement.set_Name(String value)

Thanks for making this BTW, very handy and being able to create multiple Y axes and mouseover the graph for point data is invaluable.

**Comment by nwdamgaard** [comment]
I published an update that should fix the issue - at least it fixed it for me. Let me know if you have any other problems.
